### ISSUE TITLE
[HOTFIX] 

### ISSUE THREAD

**Issue by sery270** [bookmaru/MARU-iOS#179]
### 윤진아 🎂생일🎂 축하한다아아아앗 !!!!!!!  
**오늘 좋은 하루 보내고 항상 행복한 윤진이이길 바라 🙂** 
p.s. 내가 많이 사랑해 
![image](https://user-images.githubusercontent.com/59532818/145928518-2df05fe3-7867-4b82-aef1-67d487b96857.png)

**Comment by 5anniversary** [comment]
다음생일은 어떤 사진일지... ㅎ 기대가 되네여

**Comment by 5anniversary** [comment]
클로즈~
